### ISSUE TITLE
git-clean doesn't work with branches that have been github squashed on merge

### ISSUE THREAD

**Issue by jfrost** [mcasper/git-clean#18]
Sadness ensues as the branches build up.

**Comment by mcasper** [comment]
So we're actually stuck in the middle of a massive thunderstorm right now, so I've had some time to poke at this one.

When Github squashes and rebases your branch, the resulting commit that's merged in is entirely different and would never exist on your local copy of the branch, so most of `git`'s built in "what branches are behind master?" tools won't work.

Right now, I'm thinking the easiest way to do this is to `git diff` the head of your local copy of each branch with master, and see if there are any changes. If there are none, we'll offer it up as a potential deletion, otherwise we'll assume it's still current.

@jfrost thoughts?

**Comment by jfrost** [comment]
I like it, but since it's a little sketchy, maybe we should default to `No` instead of `Yes` in this case?
